version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosec
    - gocritic
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    gosec:
      excludes:
        - G204 # Subprocess launched with variable; acceptable for controlled commands
    misspell:
      locale: US
    revive:
      severity: warning
      rules:
        - name: blank-imports
        - name: if-return

formatters:
  enable:
    - gofmt
    - goimports
