[settings]
experimental = true

[tools]
go = "1.24.9"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "v2.5.0"

[tasks.build]
description = "Compile the ghostwire binary"
run = "go build -o ghostwire ./cmd/ghostwire"

[tasks.test]
description = "Run unit tests"
run = "go test ./..."

[tasks.clean]
description = "Remove build artifacts"
run = "rm -f ghostwire"

[tasks.fmt]
description = "Format Go code"
run = "go fmt ./..."

[tasks.vet]
description = "Run go vet for static analysis"
run = "go vet ./..."

[tasks.lint]
description = "Run golangci-lint"
run = "golangci-lint run ./..."

[tasks.help]
description = "List available mise tasks"
run = "mise tasks"
