[settings]
experimental = true

[tools]
go = "1.24.9"

[tasks.build]
description = "Compile the ghostwire binary"
run = "GOCACHE=$(pwd)/.cache/go-build go build -o ghostwire ./cmd/ghostwire"

[tasks.test]
description = "Run unit tests"
run = "GOCACHE=$(pwd)/.cache/go-build go test ./..."

[tasks.clean]
description = "Remove build artifacts"
run = "rm -f ghostwire"

[tasks.fmt]
description = "Format Go code"
run = "GOCACHE=$(pwd)/.cache/go-build go fmt ./..."

[tasks.vet]
description = "Run go vet for static analysis"
run = "GOCACHE=$(pwd)/.cache/go-build go vet ./..."

[tasks.lint]
description = "Run golangci-lint"
run = "mkdir -p $(pwd)/.cache/golangci-lint && XDG_CACHE_HOME=$(pwd)/.cache GOCACHE=$(pwd)/.cache/go-build GOLANGCI_LINT_CACHE=$(pwd)/.cache/golangci-lint golangci-lint run ./..."

[tasks.help]
description = "List available mise tasks"
run = "mise tasks"
